# Generated by Django 3.2.6 on 2022-11-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcategory', to='category.category')),
            ],
        ),
    ]
